# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url:  http://knight1726.github.io

twitter_username:
github_username:

# Build settings
markdown: kramdown
